export const SIGN_UP_REQUEST="SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS="SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR="SIGN_UP_ERROR";

export const LOG_IN_REQUEST="LOG_IN_REQUEST";
export const LOG_IN_SUCCESS="LOG_IN_SUCCESS";
export const LOG_IN_ERROR="LOG_IN_ERROR";

export const VIEWPOLL_REQUEST="VIEWPOLL_REQUEST";
export const VIEWPOLL_SUCCESS="VIEWPOLL_SUCCESS";
export const VIEWPOLL_ERROR="VIEWPOLL_ERROR";